=== imShazzo/1DAW/LMSGI/DTD/LMSGI_UT4_2_10.dtd
<!ELEMENT prision (director,direccion,funcionarios,reclusos,celdas)*> 
<!ATTLIST prision
          codigoprision ID #REQUIRED
          fechap CDATA #REQUIRED
          capacidad CDATA #REQUIRED          
          >         
<!ELEMENT director (nombred,apellidosd,fechan)>
<!ELEMENT nombred (#PCDATA)> 
<!ELEMENT apellidosd (#PCDATA)> 
<!ELEMENT fechan (#PCDATA)> 
<!ELEMENT direccion (nombrevia,numero,CP,localidad,provincia)>
<!ELEMENT nombrevia (#PCDATA)> 
<!ELEMENT numero (#PCDATA)> 
<!ELEMENT CP (#PCDATA)> 
<!ELEMENT localidad (#PCDATA)> 
<!ELEMENT provincia (#PCDATA)> 
<!ELEMENT funcionarios (funcionario)+>
<!ELEMENT funcionario (fechainc,nombref)>
<!ATTLIST funcionario puesto (carcelero|administrativo|servicios) "carcelero">
<!ELEMENT fechainc (#PCDATA)> 
<!ELEMENT nombref (#PCDATA)> 
<!ELEMENT reclusos (recluso)*>
<!ELEMENT recluso (fechaing,nombrer,condena)>
<!ATTLIST recluso
          numeror ID #REQUIRED
          celda IDREF #REQUIRED
          peligrosidad (NP|PP|P|MP) #REQUIRED>
<!ELEMENT fechaing (#PCDATA)> 
<!ELEMENT nombrer (#PCDATA)> 
<!ELEMENT condena (#PCDATA)> 
<!ELEMENT celdas (celda)+>
<!ELEMENT celda (pabellon,capacidad)>
<!ATTLIST celda numcelda ID #REQUIRED>
<!ELEMENT pabellon (#PCDATA)> 
<!ELEMENT capacidad (#PCDATA)>

=== imShazzo/1DAW/LMSGI/DTD/Ej1.10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE prision SYSTEM "LMSGI_UT4_2_10.dtd">

<prision codigoprision="NIGG" fechap="12-08-15" capacidad="87134">
    <director>
        <nombred>NIGG</nombred>
        <apellidosd>Nigg</apellidosd>
        <fechan>11-9-2001</fechan>
    </director>
    <direccion>
        <nombrevia>Calle epstein</nombrevia>
        <numero>5</numero>
        <CP>30820</CP>
        <localidad>Nigg</localidad>
        <provincia>dou</provincia>
    </direccion>
    <funcionarios>
        <funcionario puesto="administrativo">
            <fechainc>10-11-2006</fechainc>
            <nombref>Breathe</nombref>
        </funcionario>
    </funcionarios>
    <reclusos>
        <recluso numeror="12412" celda="1" peligrosidad="MP">
            <fechaing>22-10-2022</fechaing>
            <nombrer>George</nombrer>
            <condena>102</condena>
        </recluso>
    </reclusos>
    <celdas>
        <celda numcelda="12313">
            <pabellon>nigger</pabellon>
            <capacidad>76431</capacidad>
        </celda>
    </celdas>
</prision>
